"""idea.primary_color

Revision ID: a2afa1281e72
Revises: 8e9997136c5c
Create Date: 2022-12-31 14:26:30.089134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2afa1281e72'
down_revision = '8e9997136c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_color', sa.String(length=24), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_column('primary_color')

    # ### end Alembic commands ###
